//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balder.Silverlight.SampleBrowser.Samples.Data.NodesStack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Balder.Silverlight.SampleBrowser.Samples.Data.NodesStack.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Balder.Core;
        ///using Balder.Core.Math;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.NodesStack
        ///{
        ///	public class BusinessObject
        ///	{
        ///		private Coordinate _position;
        ///		public Coordinate Position
        ///		{
        ///			get { return _position; }
        ///			set { _position = value; }
        ///		}
        ///
        ///		public Color Color { get; set; }
        ///
        ///		public bool IsVisible { get; set; }
        ///	}
        ///}.
        /// </summary>
        internal static string BusinessObject_cs {
            get {
                return ResourceManager.GetString("BusinessObject_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl x:Class=&quot;Balder.Silverlight.SampleBrowser.Samples.Data.NodesStack.Content&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; 
        ///    xmlns:Controls=&quot;clr-namespace:Balder.Silverlight.Controls;assembly=Balder.Silverlight&quot; 
        ///    xmlns:Geometries=&quot;clr-namespace:Balder.Core.Objects.Geometries;assembly=Balder.Core&quot; 
        ///    xmlns:local=&quot;clr-namespace:Balder.Silverlight.SampleBrowser.Samples.Data.NodesControl&quot; 
        ///    xmlns:Vie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Content_cs {
            get {
                return ResourceManager.GetString("Content_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.ComponentModel;
        ///
        ///using Balder.Silverlight.SampleBrowser.Constants;
        ///using Balder.Silverlight.SampleBrowser.Content;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.NodesStack
        ///{
        ///	[Category(Categories.Data)]
        ///	[SamplePage(&quot;Nodes Stack&quot;)]
        ///	[Description(&quot;&quot;)]
        ///	public partial class Content
        ///	{
        ///		public Content()
        ///		{
        ///			InitializeComponent();
        ///
        ///			
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string Content_xaml_cs {
            get {
                return ResourceManager.GetString("Content_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.ObjectModel;
        ///using System.Windows.Media;
        ///using Balder.Core.Math;
        ///using Color=Balder.Core.Color;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.NodesStack
        ///{
        ///	public class ViewModel
        ///	{
        ///		public ViewModel()
        ///		{
        ///			Objects = new ObservableCollection&lt;BusinessObject&gt;
        ///			          	{
        ///			          		new BusinessObject {Color = Color.FromSystemColor(Colors.Red), Position = new Coordinate(-120, 0, 0)},
        ///			          		new BusinessObject {Color = Color.FromSystemColor(Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewModel_cs {
            get {
                return ResourceManager.GetString("ViewModel_cs", resourceCulture);
            }
        }
    }
}
