//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balder.Silverlight.SampleBrowser.Samples.Data.BarChart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Balder.Silverlight.SampleBrowser.Samples.Data.BarChart.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Geometries:Geometry x:Class=&quot;Balder.Silverlight.SampleBrowser.Samples.Data.BarChart.Bar&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; 
        ///    xmlns:Geometries=&quot;clr-namespace:Balder.Core.Objects.Geometries;assembly=Balder.Core&quot;&gt;
        ///	&lt;Geometries:Box x:Name=&quot;BarBox&quot;  Dimension=&quot;5,1,5&quot; Position=&quot;0,0,0&quot; PivotPoint=&quot;0,-0.5,0&quot; Scale=&quot;1,1,1&quot; /&gt;
        ///&lt;/Geometries:Geometry&gt;
        ///.
        /// </summary>
        internal static string Bar_xaml {
            get {
                return ResourceManager.GetString("Bar_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Balder.Core.Helpers;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.BarChart
        ///{
        ///	public partial class Bar
        ///	{
        ///		public Bar()
        ///		{
        ///			InitializeComponent();
        ///		}
        ///
        ///		public static readonly DependencyProperty&lt;Bar, double&gt; ValueProperty =
        ///			DependencyProperty&lt;Bar, double&gt;.Register(b =&gt; b.Value);
        ///		public double Value
        ///		{
        ///			get { return ValueProperty.GetValue(this); }
        ///			set
        ///			{
        ///				ValueProperty.SetValue(this,value);
        ///				Scale.Y = value/10;
        ///			}
        ///		}
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string Bar_xaml_cs {
            get {
                return ResourceManager.GetString("Bar_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Geometries:Geometry x:Class=&quot;Balder.Silverlight.SampleBrowser.Samples.Data.BarChart.BarChart&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; 
        ///    xmlns:Geometries=&quot;clr-namespace:Balder.Core.Objects.Geometries;assembly=Balder.Core&quot; 
        ///    xmlns:Controls=&quot;clr-namespace:Balder.Silverlight.Controls;assembly=Balder.Silverlight&quot; 
        ///    xmlns:local=&quot;clr-namespace:Balder.Silverlight.SampleBrowser.Samples.Data.BarChart&quot; 
        ///    xmlns: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BarChart_xaml {
            get {
                return ResourceManager.GetString("BarChart_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Collections.Specialized;
        ///using Balder.Core.Helpers;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.BarChart
        ///{
        ///	public partial class BarChart
        ///	{
        ///		private Dictionary&lt;object, BarChartValue&gt; _hashedValues;
        ///		private ObservableCollection&lt;BarChartValue&gt; _values;
        ///
        ///		public BarChart()
        ///		{
        ///			InitializeComponent();
        ///
        ///			_values = new ObservableCollection&lt;BarChartValue&gt;();
        ///			_has [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BarChart_xaml_cs {
            get {
                return ResourceManager.GetString("BarChart_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.ComponentModel;
        ///using System.Reflection;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.BarChart
        ///{
        ///	public class BarChartValue : INotifyPropertyChanged
        ///	{
        ///		private readonly object _element;
        ///		private readonly string _valueMember;
        ///
        ///		private PropertyInfo _propertyInfo;
        ///		public event PropertyChangedEventHandler PropertyChanged = (s, e) =&gt; { };
        ///
        ///		public BarChartValue(object element, string valueMember)
        ///		{
        ///			_element = element;
        ///			_valueMember = valueMember;
        ///			_prop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BarChartValue_cs {
            get {
                return ResourceManager.GetString("BarChartValue_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.ComponentModel;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.BarChart
        ///{
        ///	public class BusinessObject : INotifyPropertyChanged
        ///	{
        ///		public event PropertyChangedEventHandler PropertyChanged = (s, e) =&gt; { };
        ///
        ///		private double _value;
        ///		public double Value
        ///		{
        ///			get { return _value; }
        ///			set
        ///			{
        ///				_value = value;
        ///				OnPropertyChanged(&quot;Value&quot;);
        ///			}
        ///		}
        ///
        ///		private void OnPropertyChanged(string property)
        ///		{
        ///			PropertyChanged(this, new PropertyChangedEventArgs(p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusinessObject_cs {
            get {
                return ResourceManager.GetString("BusinessObject_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl x:Class=&quot;Balder.Silverlight.SampleBrowser.Samples.Data.BarChart.Content&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; 
        ///    xmlns:Execution=&quot;clr-namespace:Balder.Core.Execution;assembly=Balder.Core&quot; 
        ///    xmlns:View=&quot;clr-namespace:Balder.Core.View;assembly=Balder.Core&quot; 
        ///    xmlns:Lighting=&quot;clr-namespace:Balder.Core.Lighting;assembly=Balder.Core&quot; 
        ///    xmlns:local=&quot;clr-namespace:Balder.Silverlight.SampleBrows [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Content_xaml {
            get {
                return ResourceManager.GetString("Content_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.ComponentModel;
        ///using System.Windows.Media.Animation;
        ///using Balder.Silverlight.SampleBrowser.Constants;
        ///using Balder.Silverlight.SampleBrowser.Content;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.BarChart
        ///{
        ///	[Category(Categories.Data)]
        ///	[SamplePage(&quot;Bar Chart&quot;)]
        ///	[Description(&quot;Sample showing how one could build a bar chart&quot;)]
        ///	public partial class Content
        ///	{
        ///		private static readonly Random Rnd = new Random();
        ///		private Storyboard _cameraMoveStoryboard;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Content_xaml_cs {
            get {
                return ResourceManager.GetString("Content_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.BarChart
        ///{
        ///	public class ViewModel
        ///	{
        ///		private static readonly Random Rnd = new Random();
        ///		public ViewModel()
        ///		{
        ///			Objects = new ObservableCollection&lt;BusinessObject&gt;();
        ///
        ///			Objects.Add(new BusinessObject { Value = Rnd.Next(0, 100) });
        ///			Objects.Add(new BusinessObject { Value = Rnd.Next(0, 100) });
        ///			Objects.Add(new BusinessObject { Value = Rnd.Next(0, 100) });
        ///		}
        ///
        ///		public Obs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewModel_cs {
            get {
                return ResourceManager.GetString("ViewModel_cs", resourceCulture);
            }
        }
    }
}
